FluxoDeCaixa/Controllers/InflowController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FluxoDeCaixa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluxoDeCaixa.Repositories;
using FluxoDeCaixa.Models.ViewModels;
using System.Globalization;
using System.Text.Json;

namespace FluxoDeCaixa.Controllers
{
    public class InflowController : Controller
    {

        private readonly InflowRepository inflowRepository;
        private readonly PersonRepository personRepository;
        private readonly Microsoft.AspNetCore.Http.IHttpContextAccessor _contxt;
        public InflowController(NHibernate.ISession session, Microsoft.AspNetCore.Http.IHttpContextAccessor contxt)
        {
            inflowRepository = new InflowRepository(session);
            personRepository = new PersonRepository(session);
            _contxt = contxt;
        }

        // GET: PersonController
        public ActionResult Index()
        {
            var pessoa = JsonSerializer.Deserialize<Person>(_contxt.HttpContext.Session.GetString("User"));

            if (pessoa.Id == 1)
            {
                ViewBag.Total = inflowRepository.SumAmount().ToString("C2", CultureInfo.CurrentCulture);
                ViewBag.Count = inflowRepository.CountAllInflows();
                return View(inflowRepository.FindAll().ToList());
            }
            else
            {
                ViewBag.TotalUser = inflowRepository.SumAmount().ToString("C2", CultureInfo.CurrentCulture);
                ViewBag.Count = inflowRepository.CountUserInflows(pessoa.Id);
                return View(inflowRepository.FindAllById(pessoa.Id).ToList());
            }
        }

        [HttpGet]
        public ActionResult SearchFilter(Filter filter)
        {
            var returnFilter = inflowRepository.SearchFilter(filter);
            double sum = 0;
            foreach(var inflow in returnFilter)
            {
                sum += inflow.InflowAmount;
            }
            ViewBag.Total = sum.ToString("C2", CultureInfo.CurrentCulture);

            return View("Index", returnFilter.ToList());
        }

        // GET: PersonController/Details/5
        public async Task<ActionResult> Details(long? id)
        { 
            if (id == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            Inflow inflow = await inflowRepository.FindByID(id.Value);
            
            if (inflow == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            return View(inflow);
        }

        // GET: PersonController/Create
        public ActionResult Create()
        {

            InflowFormViewModel inflowFormViewModel = new InflowFormViewModel() { };
            inflowFormViewModel.People = personRepository.FindAll().ToList();
            return View(inflowFormViewModel);
        }

        // POST: PersonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Inflow Inflow)
        {
            Person person = await personRepository.FindByID(Inflow.Person.Id);
            person.Balance = person.Balance + Inflow.InflowAmount;
            Inflow.Person = person;

            await inflowRepository.Add(Inflow);
            await personRepository.Update(person);

            return RedirectToAction("Index");
        }

        // GET: PersonController/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            Inflow inflow = await inflowRepository.FindByID(id.Value);
            if (inflow == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            return View(inflow);
        }

        // POST: PersonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            Inflow inflow)
        {
            if (ModelState.IsValid)
            {
                var antigo = await inflowRepository.FindByID(inflow.Id);
                antigo.InflowDate = inflow.InflowDate;
                antigo.InflowDescription = inflow.InflowDescription;
                
                await inflowRepository.Update(antigo);
                return RedirectToAction("Index");
            }

            return View(inflow);
        }

        // GET: PersonController/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            Inflow inflow = await inflowRepository.FindByID(id.Value);
            Person person = await personRepository.FindByID(inflow.Person.Id);
            person.Balance = person.Balance - inflow.InflowAmount;
            inflow.Person = person;

            if (inflow == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            await personRepository.Update(person);
            return View(inflow);
        }

        // POST: PersonController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {

            await inflowRepository.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

FluxoDeCaixa/Controllers/PersonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FluxoDeCaixa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluxoDeCaixa.Repositories;
using System.Text.Json;

namespace FluxoDeCaixa.Controllers
{
    public class PersonController : Controller
    {

        private readonly PersonRepository personRepository;
        private readonly Microsoft.AspNetCore.Http.IHttpContextAccessor _contxt;
        public PersonController(NHibernate.ISession session, Microsoft.AspNetCore.Http.IHttpContextAccessor contxt)
        {
            personRepository = new PersonRepository(session);
            _contxt = contxt;
        }

        // GET: PersonController
        public ActionResult Index()
        {
            ViewBag.Count = personRepository.CountPeople().ToString();
            return View(personRepository.FindAll().ToList());
        }

        [HttpGet]
        public ActionResult SearchFilter(Person person)
        {
            var personReturn = personRepository.FindByName(person.Name);
            return View("Index", personReturn);
        }



        // GET: PersonController/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            Person person = await personRepository.FindByID(id.Value);
            if (person == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            return View(person);
        }

        // GET: PersonController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: PersonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Person person)
        {
            if (ModelState.IsValid)
            {

                await personRepository.Add(person);
                return RedirectToAction("Index");

            }
            return View(person);
        }

        // GET: PersonController/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            Person person = await personRepository.FindByID(id.Value);
            if (person == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }

            return View(person);
        }

        // POST: PersonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            Person person)
        {
            if (ModelState.IsValid)
            {

                var antigo = await personRepository.FindByID(person.Id);
                antigo.Name = person.Name;
                antigo.Email = person.Email;
                antigo.Salary = person.Salary;
                antigo.AccountLimit = person.AccountLimit;
                antigo.MinimumValue = person.MinimumValue;
                antigo.Username = person.Username;

                await personRepository.Update(antigo);
                
                var pessoa = JsonSerializer.Deserialize<Person>(_contxt.HttpContext.Session.GetString("User"));
                if (pessoa.Id == 1)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Details", new { person.Id });
                }
            }

            return View(person);
        }

        // GET: PersonController/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            Person person = await personRepository.FindByID(id.Value);
            if (person == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(person);
        }

        // POST: PersonController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            await personRepository.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

FluxoDeCaixa/Controllers/ReportController.cs
using FluxoDeCaixa.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FluxoDeCaixa.Models.ViewModels;
using FluxoDeCaixa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;

namespace FluxoDeCaixa.Controllers
{
    public class ReportController : Controller
    {
        private readonly InflowRepository inflowRepository;
        private readonly OutflowRepository outflowRepository;
        private readonly Microsoft.AspNetCore.Http.IHttpContextAccessor _contxt;
        public ReportController(NHibernate.ISession session, Microsoft.AspNetCore.Http.IHttpContextAccessor contxt)
        {
            inflowRepository = new InflowRepository(session);
            outflowRepository = new OutflowRepository(session);
            _contxt = contxt;
        }

        // GET: ReportController
        public ActionResult Index()
        {
            ReportFormViewModel report = new ReportFormViewModel();
            var pessoa = JsonSerializer.Deserialize<Person>(_contxt.HttpContext.Session.GetString("User"));

            if (pessoa.Id == 1)
            {
                report.Inflow = inflowRepository.FindAll();
                ViewBag.CountInflows = inflowRepository.CountAllInflows().ToString();
                report.Outflow = outflowRepository.FindAll();
                ViewBag.CountOutflows = outflowRepository.CountAllOutflows().ToString();


            }
            else
            {
                report.Inflow = inflowRepository.FindAllById(pessoa.Id);
                ViewBag.CountInflows = inflowRepository.CountUserInflows(pessoa.Id); 
                report.Outflow = outflowRepository.FindAllById(pessoa.Id);
                ViewBag.CountOutflows = outflowRepository.CountUserOutflows(pessoa.Id);
            }


            return View(report);
        }


        [HttpGet]
        public ActionResult SearchFilter(Filter filter)
        {
            ReportFormViewModel returnFilter = new ReportFormViewModel();
            returnFilter.Outflow = outflowRepository.SearchFilter(filter);
            returnFilter.Inflow = inflowRepository.SearchFilter(filter);
            return View("Index", returnFilter);
        }

        // GET: ReportController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ReportController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReportController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReportController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ReportController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReportController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ReportController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FluxoDeCaixa/Views/Shared/_Layout.cshtml
@using System.Text.Json
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FluxoDeCaixa</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    @* interface admin *@

    @{ var person = JsonSerializer.Deserialize<Person>(HttpContextAccessor.HttpContext.Session.GetString("User"));
        if (person.Id == 1)
        {

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 m-1">
            
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FluxoDeCaixa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Pessoas</a></li>

                    <li class="dropdown">
                        <a class="nav-item nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Movimentações
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">

                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Inflow" asp-action="Index">Depósitos</a>
                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Outflow" asp-action="Index">Saques</a>
                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Report" asp-action="Index">Relatórios</a>
                        </div>
                    </li>
                </ul>
                <ul class="nav justify-content-end">
                        <div class="btn-group">
                            <a  class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">    Gerenciar Conta    </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item btn btn-link disabled">Usuário Admin</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item btn btn-link" asp-area="" asp-controller="Home" asp-action="Login" >Sair</a>
                            </div>
                        </div>
                    </ul>
            </div>
        
    </nav>
</header> } 
        
        
@* interface usuario *@
    else 
    {
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FluxoDeCaixa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="dropdown">
                        <a class="nav-item nav-link dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Movimentações
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">

                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Inflow" asp-action="Index">Depósitos</a>
                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Outflow" asp-action="Index">Saques</a>
                            <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Report" asp-action="Index">Relatórios</a>
                        </div>
                    </li>




                </ul>
                <ul class="nav justify-content-end">
                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">    Gerenciar Conta    </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Edit" asp-route-id="@person.Id"> Editar Conta</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item btn btn-link" asp-area="" asp-controller="Home" asp-action="Login">Sair</a>
                        </div>
                    </div>
                </ul>
            </div>
      
    </nav>
</header> 
    
 } }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FluxoDeCaixa <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>